name: CI/CD Pipeline - Projeto Cloud (.NET & K8s)

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
   
    - name: Checkout do Código
      uses: actions/checkout@v4

   
    - name: Configurar .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

   
    - name: Restaurar e Compilar a API C#
      run: |
        dotnet restore MinhaApiCoud/MinhaApiCloud.csproj
        dotnet build MinhaApiCoud/MinhaApiCloud.csproj --configuration Release

    
    - name: Build da Imagem Docker
      run: |
        docker build -t minha-api-cloud:test ./MinhaApiCoud

    
    - name: Criar Cluster Local Kubernetes (Kind)
      uses: helm/kind-action@v1.14.0
      with:
        cluster_name: kind-cluster

   
    - name: Carregar Imagem Docker no Kubernetes
      run: |
        kind load docker-image minha-api-cloud:test --name kind-cluster

   
    - name: Ajustar Imagem no Manifesto K8s
      run: |
        sed -i 's|<SEU_AZURE_REGISTRY>.azurecr.io/minha-api-cloud:v1|minha-api-cloud:test|g' K8s/deployment.yaml

    - name: Deploy e Validação no Kubernetes
      run: |
        kubectl apply -f K8s/deployment.yaml
        kubectl apply -f K8s/service.yaml
        
        echo "Aguardando os Pods ficarem prontos..."
        kubectl rollout status deployment/minha-api-deployment --timeout=90s
        
        echo "Visualizando recursos criados no K8s:"
        kubectl get all